[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "python-project-template"
version = "0.1"

[project.urls]
GitHub = "https://github.com/d33pster/python-project-template"